### ISSUE TITLE
Adjust vertical split size on opening terminal

### ISSUE THREAD

**Issue by aos** [Olical/vim-scheme#1]
Hey -- wanted to say thanks for the plugin!

I have a small request -- any chance you can provide a global variable that controls the size of the terminal split? I've made a change that does this to my local copy of your plugin but I've hardcoded the change:

```vim
function! scheme#connect()
  new
  let s:repl_term_id = termopen('mit-scheme')
  resize -10  " <<--- My change here
  normal! G
endfunction
```

Thanks a lot!

**Comment by Olical** [comment]
Hi there! That's a good idea, I'll look at adding something soon, shouldn't be too difficult. I'll just do the same as I did in vim-scotch https://github.com/Olical/vim-scotch/blob/ac7f80c07be80b6b8b003c916032508647711583/plugin/scotch.vim#L11-L13

**Comment by Olical** [comment]
I've added `g:scheme_split_size`, how's that work for you @aos?

**Comment by aos** [comment]
Perfect -- thanks @Olical !
